(lang dune 2.9)
(name pathos)
(generate_opam_files true)

(source (github gabyfle/pathos))
(authors "Gabriel Santamaria")
(maintainers "gabriel.santamaria@gabyfle.me")

(package
    (name pathos)
    (depends
        (ocaml
            (and
                (>= "4.12.0")))
        ))
