name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.12.0
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./pathos
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add pathos . --no-action
        working-directory: ${{ env.working-directory }}
      - run: opam depext pathos --yes --with-doc --with-test
        working-directory: ${{ env.working-directory }}
      - run: opam install . --deps-only --with-doc --with-test
        working-directory: ${{ env.working-directory }}
      - run: opam exec -- dune build
        working-directory: ${{ env.working-directory }}
      - run: opam exec -- dune runtest
        working-directory: ${{ env.working-directory }}
